#######               #######
########             ########
#########           #########
##########         ##########
###########       ###########
############     ############
###### ######   ###### ######        Mystic Runes
######  ###### ######  ######
######   ###########   ######     Plugin Version: 1.1
######     #######     ######       Author: _Ninjak
######                 ######
######                 ######
######                 ######
######                 ######
######                 ######

config:
  DisablePlugin: false
  Prefix: "&8[&6&lN&8]"
# the available languages are English [EN] and Polish [PL]
  Language: PL
